.Dd October 12, 2008
.Dt LMS_SOCKET_DESTROY 3
.Os
.Sh NAME
.Nm lms_socket_destroy
.Nd Destroy a socket
.Sh LIBRARY
-lmsocket
.Sh SYNOPSIS
.In msocket.h
.Ft int
.Fo lms_socket_destroy
.Fa "MSocket *ptr"
.Fc
.Sh DESCRIPTION
This function frees up all memory associated with the MSocket object referenced by
.Fa ptr
and removes it from internal lists.  This function is used for cleaning up after a socket that closed from the remote end, or closing a socket which is listening.  
To properly shut down and close an open connection socket, you should instead call 
.Fn lms_socket_close
which calls 
.Fn lms_socket_destroy
once it has finished cleanly shutting down the connection.  
.Pp
Returns 0 on success, or <0 to indicate an error condition.  
.Sh SEE ALSO
.Xr lms_socket_create 3 ,
.Xr lms_socket_close 3
