.Dd October 12, 2008
.Dt LMS_RAND_GET 3
.Os
.Sh NAME
.Nm lms_rand_get
.Nd Get some bytes of entropy
.Sh LIBRARY
-lmsocket
.Sh SYNOPSIS
.In msocket.h
.Ft int
.Fo lms_rand_get
.Fa "size_t bytes"
.Fa "unsigned char *dst"
.Fc
.Sh DESCRIPTION
The
.Fn lms_rand_get
function returns zero on success and non-zero to indicate failure.  Upon success, the 
.Fa dst 
buffer (which the caller must allocate appropriately) will be filled with 
.Fa bytes 
bytes of entropy from the operating system.  
