.Dd October 12, 2008
.Dt LMS_SOCKET_CREATE 3
.Os
.Sh NAME
.Nm lms_socket_create
.Nd Create a new MSocket object
.Sh LIBRARY
-lmsocket
.Sh SYNOPSIS
.In msocket.h
.Ft MSocket *
.Fo lms_socket_create
.Fa "int16_t type"
.Fc
.Sh DESCRIPTION
.Sh SEE ALSO
.Xr lms_socket_close 3 ,
.Xr lms_socket_destroy 3 ,
.Xr lms_socket_iconn 3 ,
.Xr lms_socket_ilisten 3
