.Dd October 12, 2008
.Dt MSOCKET 3
.Os
.Sh NAME
.Nm libmsocket
.Nd MSocket library
.Sh LIBRARY
-lmsocket
.Sh SYNOPSIS
.In msocket.h
.Ft int
.Fo lms_version_int
.Fc
.Ft char *
.Fo lms_version
.Fc
.Sh DESCRIPTION
The 
.Fn lms_version_int 
function returns an integer representing the version of the library which is currently linked to the running program.
.Pp
The 
.Fn lms_version_int 
function returns a string pointer containing a human-readable form of the version of the library which is currently linked to the running program.
.Sh SEE ALSO
.Xr lms_init 3 ,
.Xr lms_loop 3
